-- Gerado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   em:        2025-05-29 17:41:17 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g



DROP TABLE T_FV_CONTATO CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_ENDERECO CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_ESTACAO_TRATAMENTO CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_FORNECEDOR CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_MATERIAL CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_REGISTRO_MEDIDA CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_RESPONSAVEL CASCADE CONSTRAINTS 
;

DROP TABLE T_FV_SENSOR CASCADE CONSTRAINTS 
;

DROP SEQUENCE SEQ_ID_SENSOR;

DROP SEQUENCE SEQ_ID_ESTACAO;

DROP SEQUENCE SEQ_ID_ENDERECO;

DROP SEQUENCE SEQ_ID_CONTATO;

DROP SEQUENCE SEQ_ID_MATERIAL;


CREATE SEQUENCE SEQ_ID_SENSOR START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ID_ESTACAO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ID_ENDERECO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ID_CONTATO START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ID_MATERIAL START WITH 1 INCREMENT BY 1;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE T_FV_CONTATO 
    ( 
     ID_CONTATO    INTEGER  NOT NULL , 
     DS_TELEFONE   VARCHAR2 (14)  NOT NULL , 
     DS_EMAIL      VARCHAR2 (100)  NOT NULL , 
     DS_CPF        CHAR (11) , 
     DS_CNPJ       VARCHAR2 (14) 
    ) 
;

COMMENT ON COLUMN T_FV_CONTATO.ID_CONTATO IS 'ID DO CONTATO' 
;

COMMENT ON COLUMN T_FV_CONTATO.DS_TELEFONE IS 'NUMERO DE TELEFONE PARA CONTATO' 
;

COMMENT ON COLUMN T_FV_CONTATO.DS_EMAIL IS 'EMAIL PARA CONTATO' 
;

ALTER TABLE T_FV_CONTATO 
    ADD CONSTRAINT T_FV_CONTATO_PK PRIMARY KEY ( ID_CONTATO ) ;

CREATE TABLE T_FV_ENDERECO 
    ( 
     ID_ENDERECO INTEGER  NOT NULL , 
     DS_PAIS     VARCHAR2 (32)  NOT NULL , 
     DS_ESTADO   VARCHAR2 (64)  NOT NULL , 
     DS_CIDADE   VARCHAR2 (64)  NOT NULL , 
     DS_RUA      CLOB  NOT NULL , 
     DS_CEP      VARCHAR2 (8) 
    ) 
;

COMMENT ON COLUMN T_FV_ENDERECO.ID_ENDERECO IS 'ID DO ENDERECO' 
;

COMMENT ON COLUMN T_FV_ENDERECO.DS_PAIS IS 'PAIS ONDE ESTA LOCALIZADO O FORNECEDOR' 
;

COMMENT ON COLUMN T_FV_ENDERECO.DS_ESTADO IS 'ESTADO ONDE ESTA LOCALIZADO O FORNECEDOR' 
;

COMMENT ON COLUMN T_FV_ENDERECO.DS_CIDADE IS 'CIDADE ONDE ESTA LOCALIZADO O FORNECEDOR' 
;

COMMENT ON COLUMN T_FV_ENDERECO.DS_RUA IS 'RUA ONDE ESTA LOCALIZADO O FORNECEDOR' 
;

COMMENT ON COLUMN T_FV_ENDERECO.DS_CEP IS 'CEP DO FORNECEDOR' 
;

ALTER TABLE T_FV_ENDERECO 
    ADD CONSTRAINT T_FV_ENDERECO_PK PRIMARY KEY ( ID_ENDERECO ) ;

CREATE TABLE T_FV_ESTACAO_TRATAMENTO 
    ( 
     ID_ESTACAO_TRATAMENTO INTEGER  NOT NULL , 
     DT_INSTALACAO         DATE  NOT NULL , 
     ST_ESTACAO            CHAR (1) DEFAULT 'I'  NOT NULL , 
     DS_CPF                CHAR (11) 
    ) 
;

ALTER TABLE T_FV_ESTACAO_TRATAMENTO 
    ADD CONSTRAINT C_FV_ST_ESTACAO 
    CHECK (ST_ESTACAO IN ('A', 'I', 'M')) 
;

COMMENT ON COLUMN T_FV_ESTACAO_TRATAMENTO.ID_ESTACAO_TRATAMENTO IS 'ID DA ESTAÇÃO DE TRATAMENTO' 
;

COMMENT ON COLUMN T_FV_ESTACAO_TRATAMENTO.ST_ESTACAO IS 'STATUS DAS ESTACAO: ''A'' - ATIVA, ''M'' - MANUTENCAO, ''I'' - INATIVA.' 
;

ALTER TABLE T_FV_ESTACAO_TRATAMENTO 
    ADD CONSTRAINT T_FV_ESTACAO_TRATAMENTO_PK PRIMARY KEY ( ID_ESTACAO_TRATAMENTO ) ;

CREATE TABLE T_FV_FORNECEDOR 
    ( 
     DS_CNPJ       VARCHAR2 (14)  NOT NULL , 
     NM_FORNECEDOR CLOB  NOT NULL , 
     ID_ENDERECO   INTEGER  NOT NULL 
    ) 
;

CREATE UNIQUE INDEX T_FV_FORNECEDOR__IDX ON T_FV_FORNECEDOR 
    ( 
     ID_ENDERECO ASC 
    ) 
;

ALTER TABLE T_FV_FORNECEDOR 
    ADD CONSTRAINT T_FV_FORNECEDOR_PK PRIMARY KEY ( DS_CNPJ ) ;

CREATE TABLE T_FV_MATERIAL 
    ( 
     ID_MATERIAL      INTEGER  NOT NULL , 
     NM_MATERIAL      CLOB  NOT NULL , 
     TP_MATERIAL      VARCHAR2 (32)  NOT NULL , 
     NR_QUANT_ESTOQUE NUMBER (10)  NOT NULL , 
     NR_PRECO_UNIDADE NUMBER (10,2)  NOT NULL , 
     DS_CNPJ          VARCHAR2 (14)  NOT NULL 
    ) 
;

ALTER TABLE T_FV_MATERIAL 
    ADD CONSTRAINT C_FV_TP_MATERIAL 
    CHECK (TP_MATERIAL IN ('ELETRONICO', 'FILTRO', 'RESERVATORIO', 'SENSOR')) 
;

COMMENT ON COLUMN T_FV_MATERIAL.ID_MATERIAL IS 'ID DO MATERIAL' 
;

COMMENT ON COLUMN T_FV_MATERIAL.NM_MATERIAL IS 'NOME COMPLETO DO MATERIAL' 
;

COMMENT ON COLUMN T_FV_MATERIAL.TP_MATERIAL IS 'TIPO GENERICO DO MATERIAL' 
;

COMMENT ON COLUMN T_FV_MATERIAL.NR_QUANT_ESTOQUE IS 'QUANTIDADE EM ESTOQUE' 
;

COMMENT ON COLUMN T_FV_MATERIAL.NR_PRECO_UNIDADE IS 'PRECO DOS MATERIAIS' 
;

ALTER TABLE T_FV_MATERIAL 
    ADD CONSTRAINT T_FV_MATERIAL_PK PRIMARY KEY ( ID_MATERIAL ) ;

CREATE TABLE T_FV_REGISTRO_MEDIDA 
    ( 
     ID_REGISTRO  VARCHAR2 (64)  NOT NULL , 
     DT_REGISTRO  DATE  NOT NULL , 
     NR_RESULTADO NUMBER (12,4)  NOT NULL , 
     ID_SENSOR    INTEGER  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_FV_REGISTRO_MEDIDA.ID_REGISTRO IS 'IDENTIFICADOR DO REGISTRO' 
;

ALTER TABLE T_FV_REGISTRO_MEDIDA 
    ADD CONSTRAINT T_FV_REGISTRO_MEDIDA_PK PRIMARY KEY ( ID_REGISTRO ) ;

CREATE TABLE T_FV_RESPONSAVEL 
    ( 
     DS_CPF         CHAR (11)  NOT NULL , 
     NM_RESPONSAVEL CLOB  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_FV_RESPONSAVEL.DS_CPF IS 'CPF DO RESPONSAVEL' 
;

COMMENT ON COLUMN T_FV_RESPONSAVEL.NM_RESPONSAVEL IS 'NOME DO RESPONSAVEL' 
;

ALTER TABLE T_FV_RESPONSAVEL 
    ADD CONSTRAINT T_FV_RESPONSAVEL_PK PRIMARY KEY ( DS_CPF ) ;

CREATE TABLE T_FV_SENSOR 
    ( 
     ID_SENSOR             INTEGER  NOT NULL , 
     TP_SENSOR             VARCHAR2 (32)  NOT NULL , 
     TP_MEDIDA             CHAR (10) , 
     ID_ESTACAO_TRATAMENTO INTEGER  NOT NULL 
    ) 
;

COMMENT ON COLUMN T_FV_SENSOR.ID_SENSOR IS 'ID DO SENSOR' 
;

COMMENT ON COLUMN T_FV_SENSOR.TP_SENSOR IS 'TIPO DE SENSOR' 
;

COMMENT ON COLUMN T_FV_SENSOR.TP_MEDIDA IS 'TIPO DA MEDIDA DO SENSOR: PH,  TEMPERATURA, NTU' 
;

ALTER TABLE T_FV_SENSOR 
    ADD CONSTRAINT T_FV_SENSOR_PK PRIMARY KEY ( ID_SENSOR ) ;

ALTER TABLE T_FV_CONTATO 
    ADD CONSTRAINT CONTATO_FORNECEDOR_F FOREIGN KEY 
    ( 
     DS_CNPJ
    ) 
    REFERENCES T_FV_FORNECEDOR 
    ( 
     DS_CNPJ
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE T_FV_CONTATO 
    ADD CONSTRAINT CONTATO_RESPONSAVEL_FK FOREIGN KEY 
    ( 
     DS_CPF
    ) 
    REFERENCES T_FV_RESPONSAVEL 
    ( 
     DS_CPF
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE T_FV_ESTACAO_TRATAMENTO 
    ADD CONSTRAINT ESTACAO_RESPONSAVEL_FK FOREIGN KEY 
    ( 
     DS_CPF
    ) 
    REFERENCES T_FV_RESPONSAVEL 
    ( 
     DS_CPF
    ) 
;

ALTER TABLE T_FV_FORNECEDOR 
    ADD CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY 
    ( 
     ID_ENDERECO
    ) 
    REFERENCES T_FV_ENDERECO 
    ( 
     ID_ENDERECO
    ) 
;

ALTER TABLE T_FV_MATERIAL 
    ADD CONSTRAINT MATERIAL_FORNECEDOR_FK FOREIGN KEY 
    ( 
     DS_CNPJ
    ) 
    REFERENCES T_FV_FORNECEDOR 
    ( 
     DS_CNPJ
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE T_FV_REGISTRO_MEDIDA 
    ADD CONSTRAINT REGISTRO_SENSOR_FK FOREIGN KEY 
    ( 
     ID_SENSOR
    ) 
    REFERENCES T_FV_SENSOR 
    ( 
     ID_SENSOR
    ) 
    ON DELETE CASCADE 
;

ALTER TABLE T_FV_SENSOR 
    ADD CONSTRAINT SENSOR_ESTACAO_FK FOREIGN KEY 
    ( 
     ID_ESTACAO_TRATAMENTO
    ) 
    REFERENCES T_FV_ESTACAO_TRATAMENTO 
    ( 
     ID_ESTACAO_TRATAMENTO
    ) 
    ON DELETE CASCADE 
;



-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             1
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
